version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: newsneuron_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsneuron
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5.23
    container_name: newsneuron_neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password   # user=neo4j, password=password
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
