[project]
name = "newsneuron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings>=2.10.1",
    "pydantic>=2.11.7",
    "psycopg2>=2.9.10",
    "numpy>=2.3.2",
    "sentence-transformers>=5.0.0",
    "openai>=1.97.1",
]
